### ISSUE TITLE
Problem with Mongo Servers and Default Config of Instrument Server

### ISSUE THREAD

**Issue by aidanj5** [nspyre-org/nspyre#13]
(Running on Windows 10, in the nspyre conda environment)
Upon running the instrument server with its default configuration, I run into an error setting up the simulated signal generator. The socket cannot be reached, it seems, which leads to the creation of an instrument with no values which cannot cooperate with the spyrelet launcher. Upon investigation, I found that my mongo servers in Services were not running. Running ">nspyre-mongodb" ran a bunch of code, but it did not restart the servers.

![image](https://user-images.githubusercontent.com/47992941/95509249-185e9580-0969-11eb-996b-80cde4383a69.png)
![image](https://user-images.githubusercontent.com/47992941/95509355-3d530880-0969-11eb-80e7-4c2bccb981a2.png)
![image](https://user-images.githubusercontent.com/47992941/95509443-61164e80-0969-11eb-8e06-a42715eece5a.png)

How do I restart my mongo servers? I tried restarting my computer, and ">nspyre-mongodb" was still not able to turn on servers despite all the code running.

**Comment by jacobfeder** [comment]
It looks like the mongodb server is running. Run the command `mongo` and it should bring up the mongodb console like:

```
Enable MongoDB's free cloud-based monitoring service, which will then receive and display
metrics about your deployment (disk utilization, CPU, operation statistics, etc).

The monitoring data will be available on a MongoDB website with a unique URL accessible to you
and anyone you share the URL with. MongoDB may use this information to make product
improvements and to suggest MongoDB products and deployment options to you.

To enable free monitoring, run the following command: db.enableFreeMonitoring()
To permanently disable this reminder, run the following command: db.disableFreeMonitoring()
---

NSpyreSet:PRIMARY> 
```

If you see the `NSpyreSet:PRIMARY> ` shell prompt, then mongodb is running. Type `quit()` to exit.

I think the simulated lantz signal generator is simply not connect. You can run this with `lantz-sims fungen tcp`. Let me know if that works.

**Comment by aidanj5** [comment]
Ah, thanks Jacob. It works now. I guess I am not sure how much has changed and how much has stayed the same due to the redesign.

**Comment by mtsolmn** [comment]
@aidanj5 in addition to @jacobfeder comments above, the _instrument server_ will not start if the mongodb database is not running and it will tell you:

```
❯ nspyre-inserv
2020-10-08 17:09:40,465 -- INFO -- starting instrument server...
2020-10-08 17:09:40,471 -- INFO -- loaded config files ['/path/to/miniconda3/envs/nspyre/lib/python3.8/site-packages/nspyre/config/server_default_config.yaml']
2020-10-08 17:09:40,472 -- INFO -- connecting to mongodb server [mongodb://localhost:27017/]...
2020-10-08 17:09:40,531 -- INFO -- connected to mongodb server [mongodb://localhost:27017/]
```

Sorry the documentation isn't up-to-date yet, I guess you could say you are running a pre-release as we haven't merged it yet! But the documentation is coming soon, just been busy squashing the remaining bugs
