### ISSUE TITLE
nspyre-config delete item, not resetting active config

### ISSUE THREAD

**Issue by JKarsch** [nspyre-org/nspyre#14]
nspyre-config -a [new file]
... -s 2
... -d 1
but doesn't reset default config file

**Comment by mtsolmn** [comment]
hi @jck245, can you provide a more detailed description of your problem, preferably with a reproducible example of the issue

**Comment by jck245** [comment]
I was setting a new config file as the default. The previous default was listed as 1, and the new one was 2. I set the new one to default with
`nspyre-config inserv -s 2`
then deleted the old one with
`nspyre-config inserv -d 1`
but when I looked at the list again, my new file was listed as 1 (as expected) but no longer marked as the default.

**Comment by jacobfeder** [comment]
fixed in 0.4.0
