### ISSUE TITLE
PySignal slots not disconnecting properly

### ISSUE THREAD

**Issue by jacobfeder** [nspyre-org/nspyre#18]
Recreation steps:
- open instrument manager (IM)
- open spyrelet launcher (SL)
- close SL
- close IM

Errors are thrown during the on_about_to_disconnect() when trying to disconnect the PySignal slots.

**Comment by mtsolmn** [comment]
Did you confirm it's with the `on_about_to_disconnect`?

**Comment by jacobfeder** [comment]
yes it's shown in the stack trace

**Comment by jacobfeder** [comment]
Should be fixed in 0.4.3
