### ISSUE TITLE
Main NSpyre GUI Not Working

### ISSUE THREAD

**Issue by aidanj5** [nspyre-org/nspyre#20]
Upon loading up nspyre 0.4, I went through nspyre-mongodb, lantz-sims fungen tcp, and nspyre-inserv to start up the test instruments & spyrelets and make sure everything worked. I brought up the main nspyre gui to open the new instrument manager to test out the new features, and waited for the widget to pop up. It never did. I tried opening the other windows as well, including data explorer.

Also, my site-packages in my folder say that the distribution package is from version 0.3. I don't know if that's an issue, or if that could possibly be related. Just thought I would bring it up.

![image](https://user-images.githubusercontent.com/47992941/99009134-1b6f1780-250d-11eb-9dce-b54d9aebd553.png)
![image](https://user-images.githubusercontent.com/47992941/99009215-3a6da980-250d-11eb-842d-0ba7d7091cc8.png)

**Comment by aidanj5** [comment]
To be clear, the instrument manager, spyrelet launcher, and view manager all work when called from the folder. The main GUI is where the problem is located.

**Comment by jacobfeder** [comment]
This should be fixed in 0.4.3
