### ISSUE TITLE
Decreased Instrument & View Manager Functionality

### ISSUE THREAD

**Issue by aidanj5** [nspyre-org/nspyre#21]
![image](https://user-images.githubusercontent.com/47992941/99113564-1bc2ed80-25b5-11eb-9fc4-cc546288f64f.png)

The most significant issue is that I cannot read a value in my view_manager widget that should exist, which I know from the terminal. This may be because I use a simulated DAQ on my computer. However, there was no problem with setting and reading values on the old instrument manager. I hope to be able to test this at the start of next week with an actual DAQ, but there is one thing that should be cleared up first:
My minimum step in nspyre/gui/widgets/feat.py is a millimeter. When I increment my position in the view_manager, I go up by one mum, milli micrometer. Not only does that unit not exist, but this also means that the view manager interprets the base unit as "um," which is not the base unit, "m." This might lead to serious problems down the line, but in the short term it breaks our hack to control the incrementation in the view manager.

Also, my instrument manager is now of a different style, and it no longer has autoscaling features while enlarging the window. Hopefully this will be fixed.

**Comment by aidanj5** [comment]
To confirm there is now a problem with using a simulated DAQ, I will attach two screenshots below of what happens when taking a 2 dimensional position scan using an FSM. In the new version, I get no result:
![image](https://user-images.githubusercontent.com/47992941/99116232-4616aa00-25b9-11eb-8c4c-5597c750b554.png)

In the old version, I do get a result: a zero result
![image](https://user-images.githubusercontent.com/47992941/99116636-f71d4480-25b9-11eb-868f-e6c81cab6e85.png)

**Comment by mtsolmn** [comment]
Since _mum_ is not a real unit of measure, it will not work. With the new ViewManager, only units defined in `pint` are allowed. If you give it something else, it will simply be ignored. So your hack will no longer work.
Additionally, the base unit from a GUI perspective is not the general SI unit of measure (e.g. meter, second, gram, etc.), but specific SI unit **including** prefix. So if _um_ is set at the unit in lantz, then that is what the GUI uses to increment. The GUI has an additional smart feature, to increment by different orders of magnitude, but I do not remove if that feature is currently enabled or disabled.
Jacob and Uri has spoken about being able to set the step size for incrementation, but we haven't implemented this yet.

**Comment by aidanj5** [comment]
To be clear, _mum_ most certainly is not a real unit of measurement. However, it displays _mum_ due to some error.
Here is a picture of what the values look like before trying to increment.
![image](https://user-images.githubusercontent.com/47992941/99118366-0356d100-25bd-11eb-931d-6007f27f6329.png)
Here is a picture after incrementing x.
![image](https://user-images.githubusercontent.com/47992941/99118392-123d8380-25bd-11eb-9e78-a5d4d5597ebd.png)

This is not incrementing properly, and I think it is because, as you said, the base unit is the SI unit including the prefix. This did not use to be the case, though. When I increment in the previous nspyre, my original unit is 'm,' and it then steps to a unit of 'mm.' I will attach a picture. (This is with the same exact driver. My driver says units of 'um,' but it interprets only the base unit.

![image](https://user-images.githubusercontent.com/47992941/99118892-f2f32600-25bd-11eb-8574-253a32ef46a1.png)
![image](https://user-images.githubusercontent.com/47992941/99118919-ff777e80-25bd-11eb-9b09-3f2b5039b8dc.png)
![image](https://user-images.githubusercontent.com/47992941/99118947-0a321380-25be-11eb-85d5-8816187c27eb.png)
![image](https://user-images.githubusercontent.com/47992941/99118971-174f0280-25be-11eb-9cee-7dc12683049e.png)

**Comment by aidanj5** [comment]
Also, I neglected to mention this, but I don't see any actions on the new instrument_manager, even though they exist on the old one. Once again, I am using the exact same drivers.

**Comment by mtsolmn** [comment]
> Also, I neglected to mention this, but I don't see any actions on the new instrument_manager, even though they exist on the old one. Once again, I am using the exact same drivers.

All the actions you've listed are default lantz driver actions, which are used internally and should not be used by the end user or in the View Manager, so they have been removed from the GUI. If you implement your own Actions, they will appear.

**Comment by aidanj5** [comment]
Ah, ok, that's good to know. Thank you.

**Comment by jacobfeder** [comment]
Should be fixed in 0.4.3
