### ISSUE TITLE
View Manager Unable to Execute

### ISSUE THREAD

**Issue by aidanj5** [nspyre-org/nspyre#23]
I don't know if I'm missing something in my code: I am currently installing nspyre to a new computer, so I might have forgotten to include something. For instance, I did not install pyvisa. 
![image](https://user-images.githubusercontent.com/47992941/99301060-03500e80-2813-11eb-89d3-9fe9a8a3174c.png)
I am already meeting with Jacob today, so hopefully we will figure this issue out. Still, here is the error.

**Comment by jacobfeder** [comment]
Should be fixed in 0.4.3
