### ISSUE TITLE
Spyrelet Launcher and Instrument Manager Not Working

### ISSUE THREAD

**Issue by aidanj5** [nspyre-org/nspyre#26]
Upon entering the /gui/ folder and running the instrument manager (maybe not supposed to run after typing "python instrument_manager.py") and the spyrelet launcher (supposed to run after typing "python launcher.py"), I get the following errors.

![image](https://user-images.githubusercontent.com/47992941/100481549-06bc8300-30ba-11eb-880c-96efa29b19db.png)

**Comment by jacobfeder** [comment]
I think this should be fixed with a change to the client config file similar to the other issue you opened. Let us know if not.

**Comment by aidanj5** [comment]
Yes, you were right. Thanks for letting me know!
