### ISSUE TITLE
Instrument Server Not Working with Custom Config

### ISSUE THREAD

**Issue by aidanj5** [nspyre-org/nspyre#27]
After setting my own config files that have worked in the previous version of nspyre, I get an error in my command prompt.
![image](https://user-images.githubusercontent.com/47992941/100481685-85b1bb80-30ba-11eb-8b55-c9205c81be74.png)
This is what my config file looks like.
![image](https://user-images.githubusercontent.com/47992941/100481716-a11cc680-30ba-11eb-90be-2b1734fe24e8.png)

![image](https://user-images.githubusercontent.com/47992941/100481706-98c48b80-30ba-11eb-9d73-ad3c2d3f641e.png)

**Comment by jacobfeder** [comment]
Hey aidan, there were some changes in the new version what config file entries look like for both the inserv and client. See:
https://github.com/nspyre-org/nspyre/blob/develop/src/nspyre/config/client_default_config.yaml
and
https://github.com/nspyre-org/nspyre/blob/develop/src/nspyre/config/server_default_config.yaml

**Comment by aidanj5** [comment]
You're right, you removed the server info at the beginning. Thank you, I didn't spot that when evaluating the new example files, and now it works.
