### ISSUE TITLE
Instrument Manager Flaw - Units Converting

### ISSUE THREAD

**Issue by aidanj5** [nspyre-org/nspyre#29]
I noticed something when I was restarting the instrument manager. I'm going to take you through several pictures to lay it out, but very shortly: there seems to be a problem with automatically converting units at the start of the instrument manager code, instead of somewhere in the driver.

The first event is when I scale my x by 10mm. This is incrementing once on the arrows. In the driver, the units are in 'um,' but fortunately the code now adapts so that it treats 'm' as the proper base unit.
![image](https://user-images.githubusercontent.com/47992941/100641958-c6e5dd80-32fd-11eb-8613-c7e5c1ae07a3.png)
Upon restarting the IM, the result doesn't keep. This is good, because 10mm is above my upper bound of what the value can be set to. 
![image](https://user-images.githubusercontent.com/47992941/100642019-da914400-32fd-11eb-862e-a5d3b7da4839.png)

Now, if I instead increment it by 10 um (which I get by typing) you'll notice something peculiar on the restart.
![image](https://user-images.githubusercontent.com/47992941/100642157-0a404c00-32fe-11eb-83ab-450adb88aed2.png)
The 10 um becomes 10 m when I restart the instrument server!! Luckily it's not reading the value into the DAQ, and I can easily remove it by adding a 'u' to the field.
![image](https://user-images.githubusercontent.com/47992941/100642254-2d6afb80-32fe-11eb-9b6a-8c2245986975.png)

I'll briefly show that the same sort of thing happens with 10 nm. It becomes 10 um.
![image](https://user-images.githubusercontent.com/47992941/100642340-496e9d00-32fe-11eb-837d-fdc58216f7c4.png)
![image](https://user-images.githubusercontent.com/47992941/100642382-54c1c880-32fe-11eb-88eb-2819f79302bb.png)

Fortunately, this can be fixed by vigilance of the user, and so it's not imperative to the code functioning. Still, it might be harder to spot in other code.

**Comment by jacobfeder** [comment]
Thanks @aidanj5 . I've fixed this and it will be reflected in the next update.
