### ISSUE TITLE
Experiment Specific - Experiment Stuck without Error

### ISSUE THREAD

**Issue by aidanj5** [nspyre-org/nspyre#37]
When we use experiments that perform a line-scan, either for raster scan imaging or spatial feedback optimization, the code suddenly stops. We do not receive an error, and only receive an error if we try to run another spyrelet that uses the same reading functionality. 

For instance, when we run our spatial feedback optimization spyrelet, it will suddenly stop in the middle of an iteration of our search. However, the spyrelet button still says "stop," as if it was running. If we then run a Rabi spyrelet, we get an error for using the same reading task that is reserved for the other spyrelet. But, it also tells us that it was stuck using the line-scan in some way.

In spatial feedback, when this happens, it is doing the third line-scan in the y-direction, which we have controlled by the FSM through the daq. In planescan, our raster-scanning spyrelet, it gets stuck when acquiring the line-scan data into mongo.

This will just happen randomly.

Here's the code in text for the issue in planescan. Note that we also get the error when we forcefully exit the spyrelet launcher by pressing the x in the top right of the window. I believe that's what the first couple of lines mean.
```
[stderr] Traceback (most recent call last):
[stderr]   File "C:\NSpyre\miniconda3\envs\nspyre\lib\site-packages\rpyc\core\stream.py", line 268, in write
[stderr]     count = self.sock.send(data[:self.MAX_IO_CHUNK])
[stderr] ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
[stderr]
[stderr] During handling of the above exception, another exception occurred:
[stderr]
[stderr] Traceback (most recent call last):
[stderr]   File "C:\NSpyre\miniconda3\envs\nspyre\lib\site-packages\nspyre\spyrelet\spyrelet.py", line 160, in run
[stderr]     self.main(*args, **kwargs)
[stderr]   File "C:\NSpyre\nspyre_files\spyrelets\scan2D.py", line 148, in main
[stderr]     'line_data': [float(e) for e in line_data],
[stderr]   File "C:\NSpyre\nspyre_files\spyrelets\scan2D.py", line 148, in <listcomp>
[stderr]     'line_data': [float(e) for e in line_data],
[stderr]   File "C:\NSpyre\miniconda3\envs\nspyre\lib\site-packages\rpyc\core\netref.py", line 261, in method
[stderr]     return syncreq(_self, consts.HANDLE_CALLATTR, name, args, kwargs)
[stderr]   File "C:\NSpyre\miniconda3\envs\nspyre\lib\site-packages\rpyc\core\netref.py", line 63, in syncreq
[stderr]     return conn.sync_request(handler, proxy, *args)
[stderr]   File "C:\NSpyre\miniconda3\envs\nspyre\lib\site-packages\rpyc\core\protocol.py", line 473, in sync_request
[stderr]     return self.async_request(handler, *args, timeout=timeout).value
[stderr]   File "C:\NSpyre\miniconda3\envs\nspyre\lib\site-packages\rpyc\core\protocol.py", line 497, in async_request
[stderr]     self._async_request(handler, args, res)
[stderr]   File "C:\NSpyre\miniconda3\envs\nspyre\lib\site-packages\rpyc\core\protocol.py", line 479, in _async_request
[stderr]     self._send(consts.MSG_REQUEST, seq, (handler, self._box(args)))
[stderr]   File "C:\NSpyre\miniconda3\envs\nspyre\lib\site-packages\rpyc\core\protocol.py", line 263, in _send
[stderr]     self._channel.send(data)
[stderr]   File "C:\NSpyre\miniconda3\envs\nspyre\lib\site-packages\rpyc\core\channel.py", line 78, in send
[stderr]     self.stream.write(header + data + self.FLUSHER)
[stderr]   File "C:\NSpyre\miniconda3\envs\nspyre\lib\site-packages\rpyc\core\stream.py", line 273, in write
[stderr]     raise EOFError(ex)
[stderr] EOFError: [WinError 10053] An established connection was aborted by the software in your host machine
```

**Comment by aidanj5** [comment]
![image](https://user-images.githubusercontent.com/47992941/109213694-8835b700-7776-11eb-9f90-6249b09e1e5a.png)
Here is an image of where it starts to get stuck. It also oscillates around _load_tup1, _load_tup2, and _load_tup3. It ends with a maximum recursion error after running the .tag method. 

Unfortunately I don't have the second screenshot because I closed the instrument server too quickly. I apologize.

**Comment by jacobfeder** [comment]
Closing this for now - let me know if you are still having this problem and we can take a look
