### ISSUE TITLE
Code Advice - Feat for Storing Attributes in Dictionaries

### ISSUE THREAD

**Issue by aidanj5** [nspyre-org/nspyre#38]
My instrument manager is not returning what I expect / want it to.

I am working on adding functionality to my DAQ controller code for controlling my positions. I want to store certain positions in memory, and be able to move back to them at later points in time. 

I had an idea for using a dictionary - I use a Feat to set the name of an entry of a dictionary that I input. For that key, I insert my current position, which is stored as a dictionary itself.
![image](https://user-images.githubusercontent.com/47992941/110043390-edf0e880-7d0c-11eb-8873-4a61d9791eeb.png)

Using another Feat, I access that dictionary by supplying the key, once again, but this time I move to that previously set position.
![image](https://user-images.githubusercontent.com/47992941/110043551-33151a80-7d0d-11eb-824c-8f5150f25c9f.png)

The code compiles fine. When I boot up the instrument manager, I get this:
![image](https://user-images.githubusercontent.com/47992941/110044956-97d17480-7d0f-11eb-9090-7d0c61487794.png)

I think this might be because I am returning a dictionary instead of a value, and the instrument manager might not be set up to do that. Am I simply doing this wrong? Am I doing it right, but it is not supported? If not supported, will it ever be?

**Comment by jacobfeder** [comment]
The instrument manager should display whatever you return in your method decorated with @Feat (this is the "getter"). For both of the feats you have, you don't return anything. In addition, I would check out the lantz documentation on how to properly write lantz features:
https://lantz.readthedocs.io/en/0.3/tutorial/building.html

**Comment by aidanj5** [comment]
Unfortunately, the lantz documentation never featured inputting a string in a normal driver, instead of a MessageBasedDriver. It's something different than inputting a number, and so I don't know if it's actually legal either in lantz or nspyre. you are right, though, that I should check lantz forums as well.

I actually fixed my problem by reading your code in the instrument manager. I should explicitly return a string, and it will make it into a textbox. The textbox is editable then.

I'm going to make a new issue with this, but the one thing I would appreciate is to not make textboxes update with every key change -- i think that is ultra dangerous, and you can get around it by copying and pasting text from other programs. but it's really bad for quality of life.
