### ISSUE TITLE
Instrument Manager Suggestion - Text Boxes

### ISSUE THREAD

**Issue by aidanj5** [nspyre-org/nspyre#39]
I think it would be a fantastic safety feature, and a useful coding feature, if we could change the textboxes to update by pressing a button, instead of automatically updating them with every letter change.

How it currently works is that I type in a word like "origin". It does some function to the input 'o', then 'or', then 'ori', 'orig' 'origi' 'origin'. It also applies the function to an empty input ''. Since I will be moving my sample based off of text I insert, and I have an issue with repeatability in my position, it could really mess me up.

**Comment by jacobfeder** [comment]
@mtsolmn correct me if I'm wrong, but I believe this is solved now. Closing...
