### ISSUE TITLE
Logspace Acting Up

### ISSUE THREAD

**Issue by aidanj5** [nspyre-org/nspyre#43]
When I use a 'range' in my spyrelet, and set the range to a logspace instead of a linspace, I get some messed up values. For some reason, it adds on '1' of the base unit. So, when I make a range from 100ns to 1 us, I get 1.0000001 seconds to 1.000001 seconds in my range.

What can I change in the code to fix this behavior?

In fact, it doesn't seem like it even goes up to the correct value exactly.

![image](https://user-images.githubusercontent.com/47992941/122991556-c761c680-d36a-11eb-8021-13d05ac16bd1.png)
![image](https://user-images.githubusercontent.com/47992941/122992043-51aa2a80-d36b-11eb-9889-745434d11175.png)

I am using Windows 10, nspyre version 4.5. I installed via conda-forge a while ago.

**Comment by jacobfeder** [comment]
Hi Aidan,
I would recommend simply defining a 'start' and 'stop' parameter, then creating the logspace on your own in your code. We plan to remove this logspace function in later versions of nspyre anyway, because it is a bit buggy as you have observed.

**Comment by aidanj5** [comment]
Ah, so it just doesn't work. Thank you for letting me know. I'll do it myself!
