### ISSUE TITLE
Stopping a Spyrelet - While Loop

### ISSUE THREAD

**Issue by aidanj5** [nspyre-org/nspyre#44]
In ordinary spyrelets, it makes sense to write a 'for loop', iterating over some parameter. The spyrelet launcher has the option to stop the spyrelet on the next 'for loop' iteration, by clicking where the run button normally is.

I am writing a spyrelet that works slightly better as a 'while loop.' In my spatial feedback optimization spyrelet, I search, decrease my step size, and search with a smaller step size. This continues, so long as my step size is big enough. 
When I write this in a 'while loop', the launcher's stop function no longer works. I believe it's because of how it is implemented in spyrelet.py. While I am able to hack my spyrelet to work as a 'for loop,' I would rather add the functionality to NSpyre to stop a 'while loop.' Do you know how I might do that?

I am working on windows nspyre version 0.4.5. I see that there is a new version out, that I do not have the time to update to as of now. Have you fixed it in the newest version?

**Comment by jacobfeder** [comment]
Hi Aidan, can you share the code?

**Comment by mtsolmn** [comment]
I haven't looked at the code for this in a while, but from what I remember I don't think it is possible - at least with the current implementation. When you start a spyrelet in the GUI, a custom iterator object `ProgressIter` is used to go through the for loop, which allows the code to know what step in the for loop the program is at. When you stop a spyrelet with the GUI, a flag is set which is checked at the end of each cycle of the loop to determine if the program should stop. It will only stop at the end of a cycle so your code safely exits and the state is predictable. If you can do this same custom iterator object with a while loop then it should be possible, but something on the backend would have to be exposed for you to latch onto in your spyrelet code so it knows to monitor the iterator of your while loop.

I don't really see either myself or @jacobfeder working on this since we are moving away from this structure in general, but if you what to try yourself, the relevant code is here: https://github.com/nspyre-org/nspyre/blob/main/src/nspyre/gui/launcher.py in the `SpyreletRunThread`.

**Comment by aidanj5** [comment]
I'll paste the code here. I have not gotten a chance to debug it a lot, so it might have weird behavior, but this is the sort of thing I was trying to do.


`class SpatialFeedbackXYZSpyrelet(Spyrelet):

    REQUIRED_DEVICES = [
        'pulses',
        'urixyz',
    ]

    PARAMS = {
            'ctr_ch': {
                'type': str,
                'default': 'Dev1/ctr1',
            },   
            'x_initial': {
                'type': float,
                'units': 'um',
            },
            'y_initial': {
                'type': float,
                'units': 'um',
            },
            'z_initial': {
                'type': float,
                'units': 'um',
            },
            'do_z': {
                'type': bool,
                'default': True,
            },
            'sleep_time': {
                'type': float,
                'units': 's',
                'suffix': ' s',
                'default': 1
            },
            'xyz_step':{
                'type': float,
                'units': 'm',
                'default': 1e-7,
            },
            ## this value scales the search window along z, since it is less sensitive.
            ## this can be changed to a factor instead of percentage.
            'shrink_every_x_iter':{
                'type': int,
                'positive': True,
                'default': 2,
            },
            'starting_point': {
                'type': list,
                'items': list(['user_input','current_position (ignore input)']),
                'default': 'current_position (ignore input)',
            },
        }

    def main(self, ctr_ch, x_initial, y_initial, z_initial, do_z, sleep_time, xyz_step,\
            shrink_every_x_iter, starting_point):
        
        x_center = self.init_x
        y_center = self.init_y
        z_center = self.init_z
        print('starting point:', x_center, y_center, z_center)
        xyz_step = xyz_step.to('um').m
        
        '''we define step size instead of a linspace'''
        counter = 0
        
        while xyz_step >= 0.01:
            print('\n scanning z, x, y, with step size:', xyz_step)
            #print('search_x:', search_x, 'search_y:', search_y, 'search_z:', search_z)
            
            ######################################################################################
            #####  new version: iterate across z with current x and y. z travels furthest.  ######
            #####                               z scan                                      ######
            ######################################################################################
            if do_z:
                #creates logic to prevent DAQ's attempt to move piezo lower than zero.
                for e in [1, -1]:
                    keepGoing = True
                    dataZBefore = self.read(sleep_time)
                    while(keepGoing):
                        self.urixyz.daq_controller.move({'x': Q_(x_center,'um'), 'y': Q_(y_center,'um'), 'z': Q_(z_center + e * xyz_step, 'um')})
                        dataZAfter = self.read(sleep_time)
                        if dataZAfter < dataZBefore:
                            keepGoing = False
                            self.urixyz.daq_controller.move({'x': Q_(x_center,'um'), 'y': Q_(y_center,'um'), 'z': Q_(z_center, 'um')})
                        else:
                            z_center = z_center + xyz_step
                            dataZBefore = dataZAfter
                print('\n z scanned:', z_center)
                    
            #######################################################################################
            #####                                  x scan                                    ######
            #######################################################################################
            for e in [1, -1]:
                keepGoing = True
                dataZBefore = self.read(sleep_time)
                while(keepGoing):
                    self.urixyz.daq_controller.move({'x': Q_(x_center + e * xyz_step,'um'), 'y': Q_(y_center,'um'), 'z': Q_(z_center, 'um')})
                    dataZAfter = self.read(sleep_time)
                    if dataZAfter < dataZBefore:
                        keepGoing = False
                        self.urixyz.daq_controller.move({'x': Q_(x_center,'um'), 'y': Q_(y_center,'um'), 'z': Q_(z_center, 'um')})
                    else:
                        x_center = x_center + xyz_step
                        dataZBefore = dataZAfter
            print('\n x scanned:', x_center)
            #######################################################################################
            #####                                  y scan                                    ######
            #######################################################################################
            for e in [1, -1]:
                keepGoing = True
                dataZBefore = self.read(sleep_time)
                while(keepGoing):
                    self.urixyz.daq_controller.move({'x': Q_(x_center,'um'), 'y': Q_(y_center + e * xyz_step,'um'), 'z': Q_(z_center, 'um')})
                    dataZAfter = self.read(sleep_time)
                    if dataZAfter < dataZBefore:
                        keepGoing = False
                        self.urixyz.daq_controller.move({'x': Q_(x_center,'um'), 'y': Q_(y_center,'um'), 'z': Q_(z_center, 'um')})
                    else:
                        y_center = y_center + xyz_step
                        dataZBefore = dataZAfter
            print('\n y scanned:', y_center)
            counter += 1
            if counter >= shrink_every_x_iter:
                counter = 0
                xyz_step = xyz_step / 2
            
        if do_z:
            self.acquire({
                    'x_center': x_center,
                    'y_center': y_center,
                    'z_center': z_center,
                })
        else:
            self.acquire({
                    'x_center': x_center,
                    'y_center': y_center,
                    })
        print("final position:", self.urixyz.daq_controller.position)

    def read(self, deltaT):
        ctrs_start = self.urixyz.daq_controller.counter_tasks[0].read()
        time.sleep(deltaT.to('s').m)
        ctrs_end = self.urixyz.daq_controller.counter_tasks[0].read()
        dctrs = ctrs_end - ctrs_start
        ctrs_rate = dctrs / deltaT.to('s').m
        return ctrs_rate
        
        
    def initialize(self, ctr_ch, x_initial, y_initial, z_initial, do_z, sleep_time, xyz_step,\
            shrink_every_x_iter, starting_point):
        
        if starting_point == 'user_input':            
            self.urixyz.daq_controller.position = {'x': x_initial, 'y': y_initial, 'z': z_initial}
            
        self.init_x = self.urixyz.daq_controller.position['x'].to('um').m
        self.init_y = self.urixyz.daq_controller.position['y'].to('um').m
        self.init_z = self.urixyz.daq_controller.position['z'].to('um').m
        
        self.pulses.Pulser.constant(([7],0.0,0.0))   
        
        self.urixyz.new_ctr_task(ctr_ch)
        return

    def finalize(self, ctr_ch, x_initial, y_initial, z_initial, do_z, sleep_time, xyz_step,\
                shrink_every_x_iter, starting_point):
        
        return`

I suppose I'll look through that code and see if I can add it as an option without too much trouble. If not, though, I'll just change it to be a janky for-loop

**Comment by aidanj5** [comment]
Side note: the comments might be from an old version of the code, so they might not be too relevant. Do not get distracted by them.

**Comment by jacobfeder** [comment]
@aidanj5 I think the stop button in the GUI only works if you use self.progress() in your loop. It doesn't matter if it's a for loop or while loop. See if you can find a way of integrating self.progress back into the loop.

**Comment by aidanj5** [comment]
Ah, ok. I'll hopefully try that later today, and i'll let you know how it goes
- this is a somewhat hopeful timeline I have some other code to work on as well.
