### ISSUE TITLE
Instrument Manager Stepping / Unit Issues - Log Scale

### ISSUE THREAD

**Issue by aidanj5** [nspyre-org/nspyre#46]
I have updated to the latest version of NSpyre, and I am now using the gui with the step size units being able to change. This prevents me from using unitless or percentage based feats on Lantz, which is annoying, but ultimately I can change it. When adjusting my RF power with dBm, I would love to increase it with that unit, instead of saying it is milliwatts. Unfortunately, since the unit is logarithmic, I get the following error: 

![image](https://user-images.githubusercontent.com/47992941/145490128-6a7a101e-295e-4d97-9f8c-600dc738730e.png)

Can you please add functionality for dBm? In the meantime, I will put milliwatts, and hopefully no other researchers will get confused.
Also, if it's possible to add the ability to do percentage-based increases, that would be another welcome addition.

**Comment by jacobfeder** [comment]
Can you explain a bit more about how you created this error? I will try to take a look at this over winter break.
