### ISSUE TITLE
Position unit changing in spyrelets and instrument manager

### ISSUE THREAD

**Issue by uri86zvi** [nspyre-org/nspyre#9]
When using the up/down arrows to change the position of a certain channel, it moves in mm. It would be much more convenient to move it in um or allow the user to choose their step units

**Comment by mtsolmn** [comment]
hey @uri86zvi, is this baked into a specific driver you are using?

**Comment by uri86zvi** [comment]
fsm300, but I believe it is an issue with the rest of the daq based drivers
as well? My issue so far is with the fsm300, both in the spyrelet itself
and in the instrument manager

**Comment by uri86zvi** [comment]
This is a newport instrument by the way

**Comment by mtsolmn** [comment]
thanks for the info, a few things to note. We'll have to look into this, as it's either a spyrelet or a driver thing (possibly at the DAQ driver level). You should check out https://github.com/ni/nidaqmx-python and the accompanying documentation if you are coding new stuff for DAQs in the future. This is NI's relatively new python API for interfacing: it's feature complete in that it's fully connected to the NI C dll's that LabView and NI-DAQmx connects through; the current NI drivers are missing lots of functionality.

Ideally, new lantz drivers should be written at some point, but you can use nidaqmx directly in the meantime (it just won't be on the instrument server). It's on the TODO list to add a feature to add instruments without a lantz driver. I have tutorial notes on nidaqmx that will be on the nspyre docs later this week.

I'm also working on a complete rewrite of the FSM spyrelet to use the nidaqmx API directly (no lantz integration for now). But that won't be finished for a few weeks until my setup is finished.

**Comment by uri86zvi** [comment]
Thank you for your help!

**Comment by jacobfeder** [comment]
Based on a brief check of the FSM300 driver, it looks like all of the units are set in microns. I think this may be fixable by having the instrument manager step in the base units defined by the driver (in this case um). I will take a look next time I'm working on nspyre.

**Comment by jacobfeder** [comment]
Closing because this should be fixed in the next version of nspyre since the instrument manager GUI is being rewritten.

**Comment by jacobfeder** [comment]
Closing because this should be fixed in the next version of nspyre since the instrument manager GUI is being rewritten.
